#!/usr/bin/env bash
# ==============================================================================
# THEME CONTROLLER
# Manages wallpaper + matugen. All app restarts are handled by matugen
# post_hooks in config.toml — this script does not touch running processes.
# ==============================================================================

set -euo pipefail

# --- CONFIGURATION ---
readonly WALL_DIR="${HOME}/Wallpapers"
readonly STATE_DIR="${HOME}/.config/hypr/theme_state"
readonly STATE_FILE="${STATE_DIR}/state.conf"
readonly PUBLIC_STATE="${STATE_DIR}/state"
readonly CURRENT_WALLPAPER_DIR="${STATE_DIR}/current_wallpaper"
readonly CURRENT_WALLPAPER_FILE="${CURRENT_WALLPAPER_DIR}/current.jpg"
readonly DARK_LAST="${STATE_DIR}/dark_last"
readonly LIGHT_LAST="${STATE_DIR}/light_last"

WALLPAPER_CMD=()
WALLPAPER_DAEMON_CMD=()

# --- CONFIGURATION (cont.) ---
readonly SYSTEM_THEME_ENV="${HOME}/.config/hypr/theme_state/system_theme.env"
readonly QT_THEME_CONF="${HOME}/.config/qt6ct/qt6ct.conf"
readonly GTK_SETTINGS_SCHEMA="org.gnome.desktop.interface"
readonly FIREFOX_PROFILES_INI_NATIVE="${HOME}/.mozilla/firefox/profiles.ini"
readonly FIREFOX_PROFILES_INI_FLATPAK="${HOME}/.var/app/org.mozilla.firefox/.mozilla/firefox/profiles.ini"
readonly ZEN_PROFILES_INI="${HOME}/.config/zen/profiles.ini"

# --- LOGGING ---
log() { printf '\033[1;34m[THEME]\033[0m %s\n' "$*" >&2; }
notify() { notify-send "Theme Controller" "$1" -u "${2:-normal}" -t 3000 2>/dev/null || true; }
die() {
  log "ERROR: $*"
  notify "Error: $*" critical
  exit 1
}

# --- STATE ---

read_state() {
  THEME_MODE="dark"
  CURRENT_WALL=""
  [[ -f "$STATE_FILE" ]] || return 0
  while IFS='=' read -r key value || [[ -n "$key" ]]; do
    [[ $key =~ ^# ]] && continue
    value="${value%\"}"
    value="${value#\"}"
    case "$key" in
    THEME_MODE) THEME_MODE="$value" ;;
    CURRENT_WALL) CURRENT_WALL="$value" ;;
    esac
  done <"$STATE_FILE"
}

save_state() {
  mkdir -p "$STATE_DIR" "$CURRENT_WALLPAPER_DIR"
  cat >"$STATE_FILE" <<EOF
THEME_MODE="$THEME_MODE"
CURRENT_WALL="$CURRENT_WALL"
EOF
  echo "$([[ "$THEME_MODE" == "light" ]] && echo 1 || echo 0)" >"$PUBLIC_STATE"
  [[ -f "$CURRENT_WALL" ]] && cp "$CURRENT_WALL" "$CURRENT_WALLPAPER_FILE"

  # Persist per-mode last wallpaper for toggle memory.
  if [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" ]]; then
    local base_dir="${WALL_DIR/#\~/$HOME}"
    local mode_cap="${THEME_MODE^}"
    local mode_dir="${base_dir}/${mode_cap}"
    local should_save=true

    if [[ -d "$mode_dir" ]]; then
      local real_wall
      real_wall="$(realpath "$CURRENT_WALL")"
      local real_mode_dir
      real_mode_dir="$(realpath "$mode_dir")/"
      if [[ "$real_wall" != "$real_mode_dir"* ]]; then
        should_save=false
        log "Not saving to ${THEME_MODE}_last: wallpaper is not in ${mode_cap} pool"
      fi
    fi

    if [[ "$should_save" == "true" ]]; then
      [[ "$THEME_MODE" == "light" ]] && echo "$CURRENT_WALL" >"$LIGHT_LAST" || echo "$CURRENT_WALL" >"$DARK_LAST"
    fi
  fi

  # Apply system-wide theme settings
  set_system_theme "$THEME_MODE"
}

# --- SYSTEM THEME INTEGRATION ---

set_system_theme() {
  local mode="$1"
  log "Setting system theme to: $mode"

  # Save to environment file for shells/configs to source
  mkdir -p "$(dirname "$SYSTEM_THEME_ENV")"
  {
    echo "# Auto-generated by theme_controller.sh"
    echo "export GTK_THEME_VARIANT=\"$mode\""
    echo "export QT_STYLE_OVERRIDE=\"$([[ "$mode" == "light" ]] && echo "kvantum-light" || echo "kvantum-dark")\""
    echo "export COLORFGBG=\"$([[ "$mode" == "light" ]] && echo "7;0" || echo "0;7")\""
  } >"$SYSTEM_THEME_ENV"
  log "Updated $SYSTEM_THEME_ENV"

  # GTK: Set color-scheme using gsettings (GNOME/freedesktop portal compatible)
  set_gtk_theme "$mode"

  # Qt: Update qt6ct config if it exists
  set_qt_theme "$mode"

  # XDG Portal: Set system appearance
  set_xdg_portal_theme "$mode"

  # Firefox: keep profile prefs aligned with system mode
  set_firefox_theme "$mode"
}

set_gtk_theme() {
  local mode="$1"
  local scheme="$([[ "$mode" == "light" ]] && echo "prefer-light" || echo "prefer-dark")"

  if command -v gsettings >/dev/null 2>&1; then
    if gsettings list-schemas 2>/dev/null | grep -q "^org.gnome.desktop.interface$"; then
      gsettings set org.gnome.desktop.interface color-scheme "$scheme" 2>/dev/null || true
      gsettings set org.gnome.desktop.interface gtk-application-prefer-dark-mode \
        "$([[ "$mode" == "dark" ]] && echo "true" || echo "false")" 2>/dev/null || true
      log "Set GNOME color-scheme=$scheme"
    fi
  fi

  return 0
}

set_firefox_theme() {
  local mode="$1"
  local dark_value="$([[ "$mode" == "dark" ]] && echo "1" || echo "0")"

  # Native Firefox
  if [[ -f "$FIREFOX_PROFILES_INI_NATIVE" ]]; then
    local profiles_root="${FIREFOX_PROFILES_INI_NATIVE%/*}"
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
      [[ "$key" == "Path" ]] && _write_firefox_userjs "$profiles_root" "$value" "1" "$dark_value"
    done <"$FIREFOX_PROFILES_INI_NATIVE"
  fi

  # Flatpak Firefox
  if [[ -f "$FIREFOX_PROFILES_INI_FLATPAK" ]]; then
    local profiles_root="${FIREFOX_PROFILES_INI_FLATPAK%/*}"
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
      [[ "$key" == "Path" ]] && _write_firefox_userjs "$profiles_root" "$value" "1" "$dark_value"
    done <"$FIREFOX_PROFILES_INI_FLATPAK"
  fi

  # Zen Browser
  if [[ -f "$ZEN_PROFILES_INI" ]]; then
    local profiles_root="${ZEN_PROFILES_INI%/*}"
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
      [[ "$key" == "Path" ]] && _write_firefox_userjs "$profiles_root" "$value" "1" "$dark_value"
    done <"$ZEN_PROFILES_INI"
  fi

  log "Firefox/Zen theme set to $mode"
}

_write_firefox_userjs() {
  local profiles_root="$1"
  local raw_path="$2"
  local is_relative="$3"
  local dark_value="$4"
  local profile_dir="$raw_path"

  if [[ "$is_relative" == "1" ]]; then
    profile_dir="${profiles_root}/${raw_path}"
  fi

  [[ -d "$profile_dir" ]] || return 0

  local user_js="${profile_dir}/user.js"
  local tmp
  tmp="$(mktemp)"

  if [[ -f "$user_js" ]]; then
    grep -v 'user_pref("ui.systemUsesDarkTheme"' "$user_js" |
      grep -v 'user_pref("layout.css.prefers-color-scheme.content-override"' |
      grep -v 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets"' \
        >"$tmp" || true
  fi

  {
    cat "$tmp" 2>/dev/null || true
    echo "user_pref(\"layout.css.prefers-color-scheme.content-override\", 3);"
    echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
    echo "user_pref(\"ui.systemUsesDarkTheme\", ${dark_value});"
    echo "user_pref(\"browser.theme.content-theme\", ${dark_value});"
    echo "user_pref(\"browser.theme.toolbar-theme\", ${dark_value});"
  } >"$user_js"

  rm -f "$tmp"
}

set_qt_theme() {
  local mode="$1"
  local qt_style="Fusion"
  local qt_palette="$([[ "$mode" == "light" ]] && echo "Light" || echo "Dark")"

  if [[ -f "$QT_THEME_CONF" ]]; then
    cp "$QT_THEME_CONF" "${QT_THEME_CONF}.backup" 2>/dev/null || true
    local temp_conf
    temp_conf=$(mktemp)
    sed "s/^style=.*/style=${qt_style}/" "$QT_THEME_CONF" >"$temp_conf"
    mv "$temp_conf" "$QT_THEME_CONF"
    log "Updated Qt6 theme preference in qt6ct.conf"
  fi
}

set_xdg_portal_theme() {
  local mode="$1"
  log "XDG portal appearance: $mode (handled by xdg-desktop-portal-gtk via gsettings)"
}

# --- HELPERS ---

get_wallpapers() {
  local mode="${1:-$THEME_MODE}"
  walls=()
  local base_dir="${WALL_DIR/#\~/$HOME}"
  [[ -d "$base_dir" ]] || die "Wallpaper directory not found: $base_dir"
  [[ -r "$base_dir" ]] || die "Wallpaper directory not readable: $base_dir"

  local mode_cap="${mode^}"
  local mode_dir="${base_dir}/${mode_cap}"
  local wall_dir="$base_dir"
  local depth_args=()
  if [[ -d "$mode_dir" && -r "$mode_dir" ]]; then
    wall_dir="$mode_dir"
  else
    depth_args=(-maxdepth 1)
  fi

  mapfile -d '' walls < <(find -L "$wall_dir" "${depth_args[@]}" -type f \
    \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) \
    -print0 2>/dev/null | sort -z)
  ((${#walls[@]} > 0)) || die "No wallpapers found in $wall_dir"
  log "Found ${#walls[@]} wallpaper(s) [$(basename "$wall_dir")]"
}

ensure_swww() {
  if ((${#WALLPAPER_CMD[@]} == 0)); then
    if command -v swww >/dev/null 2>&1; then
      WALLPAPER_CMD=(swww)
      WALLPAPER_DAEMON_CMD=(swww-daemon)
    else
      die "swww not found. Install it to use wallpaper switching."
    fi
  fi

  pgrep -x "${WALLPAPER_DAEMON_CMD[0]}" >/dev/null && return 0
  log "Starting ${WALLPAPER_DAEMON_CMD[0]}..."
  "${WALLPAPER_DAEMON_CMD[@]}" --format xrgb >/dev/null 2>&1 &
  sleep 1
}

pick_transition() {
  local transitions=(simple grow center outer wipe wave)
  echo "${transitions[RANDOM % ${#transitions[@]}]}"
}

run_matugen() {
  local img="$1" mode="$2"
  local variant="${3:-}" contrast="${4:-}"
  local extra_args=()
  local lockfile="/tmp/arch_dots_theme_controller.lock"

  [[ -n "$variant" ]] && extra_args+=(--type "$variant")
  [[ -n "$contrast" ]] && extra_args+=(--contrast "$contrast")

  flock -x "$lockfile" bash -c "
    printf '\033[1;34m[THEME]\033[0m Running matugen ($mode${variant:+ $variant}${contrast:+ contrast $contrast})...\n'
    matugen image \"$img\" -m \"$mode\" --source-color-index 0 ${extra_args[*]} 9>&- 8>&- 7>&- 6>&- 5>&- 4>&- 3>&-
  " || {
    log "matugen failed — check image validity"
    return 1
  }
}

sync_current_wallpaper() {
  local img="$1"
  local transition="${2:-$(pick_transition)}"
  [[ -f "$img" ]] || return 0

  ensure_swww
  "${WALLPAPER_CMD[@]}" img "$img" \
    --transition-type "$transition" \
    --transition-duration 1 \
    --transition-fps 60
}

# --- COMMANDS ---

cmd_apply() {
  local img="$1"
  local mode="${2:-$THEME_MODE}"
  local transition="${3:-$(pick_transition)}"

  img="$(realpath "$img")"
  [[ -f "$img" ]] || die "Image not found: $img"

  ensure_swww

  log "Applying: $(basename "$img") [$mode]"

  # Fire wallpaper transition immediately
  "${WALLPAPER_CMD[@]}" img "$img" \
    --transition-type "$transition" \
    --transition-duration 2 \
    --transition-fps 60 &
  local swww_pid=$!

  # Generate colors in parallel
  run_matugen "$img" "$mode" || log "WARNING: Matugen failed, but continuing..."

  # Save state
  CURRENT_WALL="$img"
  THEME_MODE="$mode"
  save_state

  wait "$swww_pid" 2>/dev/null || true
  notify "Wallpaper applied" low
}

cmd_restore() {
  read_state
  local img="$CURRENT_WALL"

  [[ -n "$img" && -f "$img" ]] || img="$CURRENT_WALLPAPER_FILE"

  if [[ -f "$img" ]]; then
    run_matugen "$img" "$THEME_MODE" || log "WARNING: Matugen failed during restore"
    sync_current_wallpaper "$img"
    if [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" ]]; then
      save_state
    fi
  else
    log "No saved wallpaper to restore"
  fi
}

cmd_toggle() {
  read_state
  local new_mode="light"
  [[ "$THEME_MODE" == "light" ]] && new_mode="dark"
  log "Toggling → $new_mode"

  local last_file
  [[ "$new_mode" == "light" ]] && last_file="$LIGHT_LAST" || last_file="$DARK_LAST"
  local last_wall=""
  [[ -f "$last_file" ]] && last_wall="$(tr -d '[:space:]' <"$last_file")"

  if [[ -n "$last_wall" && -f "$last_wall" ]]; then
    local base_dir="${WALL_DIR/#\~/$HOME}"
    local mode_cap="${new_mode^}"
    local mode_dir="${base_dir}/${mode_cap}"
    if [[ -d "$mode_dir" ]]; then
      local real_wall
      real_wall="$(realpath "$last_wall")"
      local real_mode_dir
      real_mode_dir="$(realpath "$mode_dir")"
      if [[ "$real_wall" != "$real_mode_dir"* ]]; then
        log "Saved wallpaper for $new_mode is invalid. Ignoring."
        last_wall=""
      fi
    fi
  fi

  if [[ -n "$last_wall" && -f "$last_wall" ]]; then
    log "Restoring $(basename "$last_wall") [$new_mode]"
    cmd_apply "$last_wall" "$new_mode"
  else
    local base_dir="${WALL_DIR/#\~/$HOME}"
    local new_mode_cap="${new_mode^}"
    local new_mode_dir="${base_dir}/${new_mode_cap}"

    if [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" && -d "$new_mode_dir" ]]; then
      local wall_name
      wall_name="$(basename "$CURRENT_WALL")"
      local matching_wall
      matching_wall="$(find -L "$new_mode_dir" -type f -name "$wall_name" -print -quit)"

      if [[ -n "$matching_wall" ]]; then
        log "Found matching wallpaper in ${new_mode_cap} pool: $wall_name"
        cmd_apply "$matching_wall" "$new_mode"
        return 0
      fi
    fi

    if [[ -d "$new_mode_dir" ]]; then
      log "No matching wall or history — picking random from ${new_mode_cap} pool"
      cmd_random "$new_mode"
    elif [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" ]]; then
      run_matugen "$CURRENT_WALL" "$new_mode"
      sync_current_wallpaper "$CURRENT_WALL"
      THEME_MODE="$new_mode"
      save_state
      notify "Switched to $new_mode mode"
    else
      log "No pool or history — picking random"
      cmd_random "$new_mode"
    fi
  fi
}

cmd_random() {
  local force_mode="${1:-}"
  read_state
  [[ -z "$force_mode" ]] && force_mode="$THEME_MODE"
  get_wallpapers "$force_mode"
  local rand="${walls[RANDOM % ${#walls[@]}]}"
  cmd_apply "$rand" "$force_mode"
}

cmd_next() {
  read_state
  get_wallpapers "$THEME_MODE"
  local next=0
  if [[ -n "$CURRENT_WALL" ]]; then
    local current_real
    current_real="$(realpath "$CURRENT_WALL" 2>/dev/null || echo "$CURRENT_WALL")"
    for i in "${!walls[@]}"; do
      local wall_real
      wall_real="$(realpath "${walls[$i]}" 2>/dev/null || echo "${walls[$i]}")"
      [[ "$wall_real" == "$current_real" ]] && {
        next=$((i + 1))
        break
      }
    done
  fi
  ((next >= ${#walls[@]})) && next=0
  cmd_apply "${walls[$next]}" "$THEME_MODE"
}

cmd_set_image() {
  local img="${1:-}"
  [[ -z "$img" ]] && die "No image specified"
  [[ -f "$img" ]] || die "Image not found: $img"
  read_state
  cmd_apply "$img" "$THEME_MODE"
}

cmd_refresh() {
  local variant="${1:-}" contrast="${2:-}"
  read_state
  if [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" ]]; then
    run_matugen "$CURRENT_WALL" "$THEME_MODE" "$variant" "$contrast"
    sync_current_wallpaper "$CURRENT_WALL"
    save_state
    notify "Theme refreshed" low
  else
    cmd_random
  fi
}

cmd_tag() {
  local img="${1:-}" mode="${2:-}"
  [[ -z "$img" || -z "$mode" ]] && die "Usage: tag <image> <dark|light>"
  [[ "$mode" != "dark" && "$mode" != "light" ]] && die "Mode must be 'dark' or 'light'"
  [[ -f "$img" ]] || die "Image not found: $img"
  img="$(realpath "$img")"
  local mode_dir="${WALL_DIR}/${mode^}"
  mkdir -p "$mode_dir"
  ln -sf "$img" "${mode_dir}/$(basename "$img")"
  log "Tagged '$(basename "$img")' → $mode"
}

cmd_untag() {
  local img="${1:-}" mode="${2:-}"
  [[ -z "$img" || -z "$mode" ]] && die "Usage: untag <image> <dark|light>"
  [[ "$mode" != "dark" && "$mode" != "light" ]] && die "Mode must be 'dark' or 'light'"
  local mode_dir="${WALL_DIR}/${mode^}"
  local link="${mode_dir}/$(basename "$img")"
  [[ -L "$link" ]] || die "No tag found for '$(basename "$img")' in $mode"
  rm "$link"
  log "Untagged '$(basename "$img")' from $mode"
}

cmd_set() {
  local target_mode=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
    --mode)
      target_mode="$2"
      shift 2
      ;;
    *)
      die "Unknown argument: $1"
      ;;
    esac
  done

  [[ -z "$target_mode" ]] && die "Usage: set --mode <light|dark>"
  [[ "$target_mode" != "light" && "$target_mode" != "dark" ]] && die "Invalid mode: $target_mode"

  read_state
  log "Setting mode → $target_mode"

  if [[ -n "$CURRENT_WALL" && -f "$CURRENT_WALL" ]]; then
    run_matugen "$CURRENT_WALL" "$target_mode"
    sync_current_wallpaper "$CURRENT_WALL"
    THEME_MODE="$target_mode"
    save_state
    notify "Mode set to $target_mode"
  else
    THEME_MODE="$target_mode"
    save_state
    notify "Mode updated to $target_mode"
  fi
}

# --- INIT ---
[[ ! -d "$STATE_DIR" ]] && mkdir -p "$STATE_DIR"

case "${1:-}" in
toggle) cmd_toggle ;;
random) cmd_random "${2:-}" ;;
next) cmd_next ;;
set-image) cmd_set_image "${2:-}" ;;
restore) cmd_restore ;;
refresh) cmd_refresh "${2:-}" "${3:-}" ;;
set)
  shift
  cmd_set "$@"
  ;;
get-mode)
  read_state
  echo "$THEME_MODE"
  ;;
tag) cmd_tag "${2:-}" "${3:-}" ;;
untag) cmd_untag "${2:-}" "${3:-}" ;;
debug)
  read_state
  log "WALL_DIR: $WALL_DIR"
  log "THEME_MODE: $THEME_MODE"
  log "CURRENT_WALL: $CURRENT_WALL"
  log "DARK_LAST:  $(cat "$DARK_LAST" 2>/dev/null || echo '(none)')"
  log "LIGHT_LAST: $(cat "$LIGHT_LAST" 2>/dev/null || echo '(none)')"
  log "Dark dir:  $([ -d "${WALL_DIR}/Dark" ] && echo YES || echo NO)"
  log "Light dir: $([ -d "${WALL_DIR}/Light" ] && echo YES || echo NO)"
  get_wallpapers "$THEME_MODE"
  log "Wallpapers in current mode pool: ${#walls[@]}"
  ;;
*)
  cat <<EOF
Usage: $(basename "$0") {toggle|random|next|set-image|restore|refresh|set|get-mode|tag|untag|debug}

  toggle            Switch dark/light mode, restoring last wallpaper for that mode
  random            Random wallpaper from current mode's pool
  next              Next wallpaper alphabetically in current mode's pool
  set-image <path>  Apply a specific wallpaper
  restore           Restore the last saved wallpaper and theme
  refresh           Re-run matugen on current wallpaper
  set               Set specific parameters (e.g., --mode light)
  get-mode          Print current mode (dark/light)
  tag <img> <mode>  Symlink a wallpaper into Dark/ or Light/ pool
  untag <img> <mode> Remove a wallpaper's symlink from a mode pool
  debug             Show diagnostic info

Mode pools: ~/Wallpapers/Dark/  ~/Wallpapers/Light/
  Create symlinks here pointing to wallpapers you want for each mode.
  When a pool dir is absent, falls back to all of ~/Wallpapers/
EOF
  ;;
esac
